INFO:root:entered logger
INFO:root:0
INFO:root:Socket Closed: at 2022-04-14 11:58:52.583605;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:0
INFO:root:Socket Closed: at 2022-04-14 12:04:30.748728;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:0
INFO:root:Socket Closed: at 2022-04-14 12:06:39.126679;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:0
INFO:root:Socket Closed: at 2022-04-14 12:08:33.587430;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:object of type 'NoneType' has no len()
INFO:root:Socket Closed: at 2022-04-14 12:10:01.461889;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:0
INFO:root:Socket Closed: at 2022-04-14 12:10:59.586820;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:0
INFO:root:Socket Closed: at 2022-04-14 12:12:13.761350;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:asyncio.run() cannot be called from a running event loop
INFO:root:Socket Closed: at 2022-04-14 12:14:32.823476;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:0
INFO:root:Socket Closed: at 2022-04-14 12:21:28.161761;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:'str' object has no attribute 'timestamp'
INFO:root:Socket Closed: at 2022-04-14 14:07:50.855942;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:'str' object has no attribute 'timestamp'
INFO:root:Socket Closed: at 2022-04-14 14:15:06.714756;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:'str' object has no attribute 'timestamp'
INFO:root:Socket Closed: at 2022-04-14 14:15:42.928226;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:'str' object has no attribute 'timestamp'
INFO:root:Socket Closed: at 2022-04-14 14:16:24.579589;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:'str' object has no attribute 'timestamp'
INFO:root:Socket Closed: at 2022-04-14 14:25:29.276502;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ResourceNotFoundException) when calling the WriteRecords operation: The table sampleTable does not exist.
INFO:root:Socket Closed: at 2022-04-14 14:28:24.693867;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ResourceNotFoundException) when calling the WriteRecords operation: The table sampleTable does not exist.
INFO:root:Socket Closed: at 2022-04-14 14:31:01.891916;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ResourceNotFoundException) when calling the WriteRecords operation: The table sampleTable does not exist.
INFO:root:Socket Closed: at 2022-04-14 14:33:28.805269;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ResourceNotFoundException) when calling the WriteRecords operation: The table sampleTable does not exist.
INFO:root:Socket Closed: at 2022-04-14 14:35:33.623472;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ValidationException) when calling the WriteRecords operation: The dimension name and value exceeds the maximum supported length for dimension names and values. See Quotas in the Timestream developer guide for additional information.
INFO:root:Socket Closed: at 2022-04-14 14:38:18.274109;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ValidationException) when calling the WriteRecords operation: The dimension name and value exceeds the maximum supported length for dimension names and values. See Quotas in the Timestream developer guide for additional information.
INFO:root:Socket Closed: at 2022-04-14 14:47:19.384664;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:entered logger
INFO:root:"['symbol'] not in index"
INFO:root:Socket Closed: at 2022-04-14 14:59:16.836959;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ValidationException) when calling the WriteRecords operation: The dimension name and value exceeds the maximum supported length for dimension names and values. See Quotas in the Timestream developer guide for additional information.
INFO:root:Socket Closed: at 2022-04-14 15:00:10.757834;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ValidationException) when calling the WriteRecords operation: The dimension name and value exceeds the maximum supported length for dimension names and values. See Quotas in the Timestream developer guide for additional information.
INFO:root:Socket Closed: at 2022-04-14 15:38:10.490773;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ValidationException) when calling the WriteRecords operation: The dimension name and value exceeds the maximum supported length for dimension names and values. See Quotas in the Timestream developer guide for additional information.
INFO:root:Socket Closed: at 2022-04-14 15:54:00.021839;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ValidationException) when calling the WriteRecords operation: The dimension name and value exceeds the maximum supported length for dimension names and values. See Quotas in the Timestream developer guide for additional information.
INFO:root:Socket Closed: at 2022-04-14 15:54:52.142919;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:An error occurred (ValidationException) when calling the WriteRecords operation: The dimension name and value exceeds the maximum supported length for dimension names and values. See Quotas in the Timestream developer guide for additional information.
INFO:root:Socket Closed: at 2022-04-14 15:55:41.479532;
            close reason: None,
                close code: None
INFO:root:error occured in main body kraken-orderbook-BTC/USD
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
INFO:root:entered logger
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError(None, Close(code=1000, reason=''), None)>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1495, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1488, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 550, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 213, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 390, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 395, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 370, in uvloop.loop.Loop._ceval_process_signals
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rajmani/Documents/research/Home/python/phobos-trading-engine/py39/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/Users/rajmani/Documents/research/Home/python/phobos-trading-engine/py39/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/rajmani/Documents/research/Home/python/phobos-trading-engine/py39/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1088, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/rajmani/Documents/research/Home/python/phobos-trading-engine/py39/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1143, in read_frame
    frame = await Frame.read(
  File "/Users/rajmani/Documents/research/Home/python/phobos-trading-engine/py39/lib/python3.9/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
